// Code generated by mdatagen. DO NOT EDIT.

package gcspubsubeventreceiver

import (
	"testing"

	"go.uber.org/goleak"
)

func TestMain(m *testing.M) {
	goleak.VerifyTestMain(m,
		// The opencensus stats worker is started by the GCP SDK and cannot be stopped.
		goleak.IgnoreTopFunction("go.opencensus.io/stats/view.(*worker).start"),
	)
}
