version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
      - dependency-name: "github.com/open-telemetry/opamp-go"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/packagestate"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opamp-go"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/cmd/plugindocgen"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/updater"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opamp-go"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/internal/report"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
    commit-message:
      prefix: "deps"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/internal/tools"
    schedule:
      interval: "weekly"
    ignore:
      # Opentelemetry updates will be done manually
      - dependency-name: "github.com/open-telemetry/opentelemetry-collector*"
      - dependency-name: "go.opentelemetry.io/*"
      # keep gosec at v2.18.2
      - dependency-name: "github.com/securego/gosec/v2"
      # ignore patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    commit-message:
      prefix: "deps"
      include: "scope"
