version: 2

project_name: observiq-otel-collector

before:
  hooks:
    - make release-prep-gpg CURR_VERSION={{ .Version }}

# https://goreleaser.com/customization/build/
builds:
  - id: collector
    binary: observiq-otel-collector
    main: ./cmd/collector
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    tags:
      - bindplane
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - ppc64
      - ppc64le
    ignore:
      - goos: darwin
        goarch: ppc64
      - goos: darwin
        goarch: ppc64le
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: ppc64
      - goos: windows
        goarch: ppc64le
    ldflags:
      - -s -w
      - -X github.com/observiq/bindplane-otel-collector/version.version=v{{ .Version }}
      - -X github.com/observiq/bindplane-otel-collector/version.gitHash={{ .FullCommit }}
      - -X github.com/observiq/bindplane-otel-collector/version.date={{ .Date }}
    no_unique_dist_dir: false
  - id: updater
    binary: updater
    dir: ./updater/
    main: ./cmd/updater
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - ppc64
      - ppc64le
    ignore:
      - goos: darwin
        goarch: ppc64
      - goos: darwin
        goarch: ppc64le
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: ppc64
      - goos: windows
        goarch: ppc64le
    ldflags:
      - -s -w
      - -X github.com/observiq/bindplane-otel-collector/updater/internal/version.version=v{{ .Version }}
      - -X github.com/observiq/bindplane-otel-collector/updater/internal/version.gitHash={{ .FullCommit }}
      - -X github.com/observiq/bindplane-otel-collector/updater/internal/version.date={{ .Date }}
    no_unique_dist_dir: false

# https://goreleaser.com/customization/archive/
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - src: release_deps/config.yaml
        dst: "."
        strip_parent: true
      - src: release_deps/logging.yaml
        dst: "."
        strip_parent: true
      - src: release_deps/plugins/*
        dst: plugins
        strip_parent: true
      - src: release_deps/VERSION.txt
        dst: "."
        strip_parent: true
      - src: release_deps/com.observiq.collector.plist
        dst: "install"
        strip_parent: true
      - src: release_deps/gpg-keys.tar.gz
        dst: "."
        strip_parent: true
      - src: release_deps/windows_service.json
        dst: install
        strip_parent: true

nfpms:
  - id: collector
    ids:
      - collector
      - updater
    file_name_template: "{{ .PackageName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    package_name: observiq-otel-collector
    vendor: observIQ, Inc
    maintainer: observIQ <support@observiq.com>
    description: observIQ's distribution of the OpenTelemetry collector
    homepage: https://github.com/observIQ/bindplane-agent
    license: Apache 2.0
    formats:
      - rpm
      - deb
    bindir: /usr/share/observiq-otel-collector/stage/observiq-otel-collector
    deb:
      signature:
        key_file: "{{ .Env.SIGNING_KEY_FILE }}"
    rpm:
      signature:
        key_file: "{{ .Env.SIGNING_KEY_FILE }}"
    contents:
      # This file was previously managed by the package
      # therefore it must be marked as a ghost file to
      # prevent the package manager from deleting it
      # upon upgrade. This file will continue to be
      # used by user's to modify the package's install
      # behavior.
      - dst: /etc/sysconfig/observiq-otel-collector
        type: ghost
      # Service files previously managed by the package.
      - dst: /usr/lib/systemd/system/observiq-otel-collector.service
        type: ghost
      - dst: /etc/init.d/observiq-otel-collector
        type: ghost
      # All other files previously managed by the package
      - dst: /opt/observiq-otel-collector/observiq-otel-collector
        type: ghost
      - dst: /opt/observiq-otel-collector/updater
        type: ghost
      - dst: /opt/observiq-otel-collector
        type: ghost
      - dst: /opt/observiq-otel-collector/config.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/logging.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/LICENSE
        type: ghost
      - dst: /opt/observiq-otel-collector/VERSION.txt
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/active_directory_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/aerospike_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/apache_cassandra_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/apache_combined_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/apache_common_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/apache_http_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/bindplane_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/cisco_asa_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/cisco_catalyst_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/cisco_meraki_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/cockroachdb_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/cockroachdb_metrics.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/common_event_format_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/container_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/couchbase_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/couchbase_metrics.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/couchdb_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/csv_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/elasticsearch_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/esxi_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/file_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/hadoop_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/haproxy_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/hbase_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/iis_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/ingress_nginx_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/jboss_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/json_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/kafka_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/kubelet_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/macos_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/mongodb_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/mysql_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/nginx_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/oracle_database_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/oracledb_metrics.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/pgbouncer_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/postgresql_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/rabbitmq_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/redis_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/sap_hana_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/solr_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/sql_server_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/syslog_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/tcp_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/tomcat_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/ubiquiti_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/udp_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/vcenter_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/w3c_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/wildfly_logs.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/windows_dhcp.yaml
        type: ghost
      - dst: /opt/observiq-otel-collector/plugins/zookeeper_logs.yaml
        type: ghost
      - dst: /usr/share/observiq-otel-collector/stage/observiq-otel-collector
        type: dir
        file_info:
          mode: 0750
          owner: root
          group: root
      - src: release_deps/config.yaml
        dst: /usr/share/observiq-otel-collector/stage/observiq-otel-collector/config.yaml
        file_info:
          mode: 0640
          owner: root
          group: root
        type: config|noreplace
      - src: release_deps/logging.yaml
        dst: /usr/share/observiq-otel-collector/stage/observiq-otel-collector/logging.yaml
        file_info:
          mode: 0640
          owner: root
          group: root
        type: config|noreplace
      - src: LICENSE
        dst: /usr/share/observiq-otel-collector/stage/observiq-otel-collector/LICENSE
        file_info:
          mode: 0644
          owner: root
          group: root
      - src: release_deps/VERSION.txt
        dst: /usr/share/observiq-otel-collector/stage/observiq-otel-collector/VERSION.txt
        file_info:
          mode: 0644
          owner: root
          group: root
      - dst: /usr/share/observiq-otel-collector/stage/observiq-otel-collector/plugins
        type: dir
        file_info:
          mode: 0750 # restrict plugins to owner / group only
          owner: root
          group: root
      # Note: plugins owner/group/mode is set in the post-install script
      # Attempting to set the permissions here results in the following error:
      # nfpm failed: cannot write header of release_deps/plugins/amazon_eks.yaml to data.tar.gz: archive/tar: missed writing 1736 bytes
      - src: release_deps/plugins/*
        dst: /usr/share/observiq-otel-collector/stage/observiq-otel-collector/plugins
      # Storage dir is used by stateful receivers, such as filelog receiver. It allows
      # receivers to track their progress and buffer data.
      - dst: /usr/share/observiq-otel-collector/stage/observiq-otel-collector/storage
        type: dir
        file_info:
          mode: 0750
          owner: root
          group: root
      - dst: /usr/share/observiq-otel-collector/stage/observiq-otel-collector/log
        type: dir
        file_info:
          mode: 0750
          owner: root
          group: root
    scripts:
      preinstall: ./scripts/package/preinstall.sh
      postinstall: ./scripts/package/postinstall.sh
      preremove: ./scripts/package/preremove.sh
      postremove: ./scripts/package/postremove.sh

# https://goreleaser.com/customization/checksum/
checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-SHA256SUMS"
  algorithm: sha256
  extra_files:
    - glob: "./observiq-otel-collector*.msi"

# https://goreleaser.com/customization/sign/
signs:
  - cmd: cosign
    stdin: "{{ .Env.COSIGN_PWD }}"
    args:
      ["sign-blob", "--key=cosign.key", "--output=${signature}", "${artifact}"]
    artifacts: all

# https://goreleaser.com/customization/release/
release:
  draft: false

  # publish to a prerelease first
  prerelease: "true"
  extra_files:
    - glob: "./observiq-otel-collector*.msi"
    - glob: "./observiq-otel-collector*.msi.sig"
    - glob: "./scripts/install/install_unix.sh"
    - glob: "./scripts/install/install_macos.sh"
    - glob: "./release_deps/gpg-keys.tar.gz"

# https://console.cloud.google.com/storage/browser/bdot-release
blobs:
  - provider: gs
    bucket: bdot-release
    directory: "v{{ .Version }}"
    extra_files:
      - glob: "./observiq-otel-collector*.msi"
      - glob: "./observiq-otel-collector*.msi.sig"
      - glob: "./scripts/install/install_unix.sh"
      - glob: "./scripts/install/install_macos.sh"
      - glob: "./release_deps/gpg-keys.tar.gz"

# https://goreleaser.com/customization/changelog/
changelog:
  use: github
  sort: asc
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: "Dependencies"
      regexp: "^.*deps[(\\w)]*:+.*$"
      order: 30
    - title: Other
      order: 999
