version: 2

project_name: observiq-otel-collector

before:
  hooks:
    - make release-prep CURR_VERSION={{ .Version }}

# https://goreleaser.com/customization/build/
# https://goreleaser.com/customization/builds/#import-pre-built-binaries
builds:
  - id: collector
    builder: prebuilt
    binary: observiq-otel-collector
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - ppc64le
    prebuilt:
      path: tmp/collector_{{ .Os }}_{{ .Arch }}

# Build container images with docker buildx (mutli arch builds).
dockers:
  - id: scratch-amd64
    goos: linux
    goarch: amd64
    retry:
      attempts: 10
      delay: 30s
      max_delay: 1m
    ids:
      - collector
    image_templates:
      - "observiq/bindplane-agent-amd64:{{ .Version }}-minimal"
      - "ghcr.io/observiq/bindplane-agent-amd64:{{ .Version }}-minimal"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-amd64:{{ .Version }}-minimal"
    dockerfile: ./docker/Dockerfile.scratch
    use: buildx
    build_flag_templates:
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
      - "--platform=linux/amd64"
    extra_files:
      - release_deps/VERSION.txt
      - release_deps/plugins
      - release_deps/config.yaml
      - config/logging.stdout.yaml
      - LICENSE
  - id: scratch-arm64
    goos: linux
    goarch: arm64
    retry:
      attempts: 10
      delay: 30s
      max_delay: 1m
    ids:
      - collector
    image_templates:
      - "observiq/bindplane-agent-arm64:{{ .Version }}-minimal"
      - "ghcr.io/observiq/bindplane-agent-arm64:{{ .Version }}-minimal"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-arm64:{{ .Version }}-minimal"
    dockerfile: ./docker/Dockerfile.scratch
    use: buildx
    build_flag_templates:
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
      - "--platform=linux/arm64"
    extra_files:
      - release_deps/VERSION.txt
      - release_deps/plugins
      - release_deps/config.yaml
      - config/logging.stdout.yaml
      - LICENSE
  - id: scratch-ppc64le
    goos: linux
    goarch: ppc64le
    retry:
      attempts: 10
      delay: 30s
      max_delay: 1m
    ids:
      - collector
    image_templates:
      - "observiq/bindplane-agent-ppc64le:{{ .Version }}-minimal"
      - "ghcr.io/observiq/bindplane-agent-ppc64le:{{ .Version }}-minimal"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-ppc64le:{{ .Version }}-minimal"
    dockerfile: ./docker/Dockerfile.scratch
    use: buildx
    build_flag_templates:
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
      - "--platform=linux/ppc64le"
    extra_files:
      - release_deps/VERSION.txt
      - release_deps/plugins
      - release_deps/config.yaml
      - config/logging.stdout.yaml
      - LICENSE

  - id: ubuntu-amd64
    goos: linux
    goarch: amd64
    retry:
      attempts: 10
      delay: 30s
      max_delay: 1m
    ids:
      - collector
    image_templates:
      - "observiq/observiq-otel-collector-amd64:latest"
      - "observiq/observiq-otel-collector-amd64:{{ .Version }}"
      - "ghcr.io/observiq/observiq-otel-collector-amd64:latest"
      - "ghcr.io/observiq/observiq-otel-collector-amd64:{{ .Version }}"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-amd64:latest"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-amd64:{{ .Version }}"
      # Bindplane Agent Containers
      - "observiq/bindplane-agent-amd64:latest"
      - "observiq/bindplane-agent-amd64:{{ .Version }}"
      - "ghcr.io/observiq/bindplane-agent-amd64:latest"
      - "ghcr.io/observiq/bindplane-agent-amd64:{{ .Version }}"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-amd64:latest"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-amd64:{{ .Version }}"
    dockerfile: ./docker/Dockerfile.ubuntu
    use: buildx
    build_flag_templates:
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
      - "--platform=linux/amd64"
    extra_files:
      - release_deps/VERSION.txt
      - release_deps/plugins
      - release_deps/config.yaml
      - config/logging.stdout.yaml
      - LICENSE
  - id: ubuntu-arm64
    goos: linux
    goarch: arm64
    retry:
      attempts: 10
      delay: 30s
      max_delay: 1m
    ids:
      - collector
    image_templates:
      - "observiq/observiq-otel-collector-arm64:latest"
      - "observiq/observiq-otel-collector-arm64:{{ .Version }}"
      - "ghcr.io/observiq/observiq-otel-collector-arm64:latest"
      - "ghcr.io/observiq/observiq-otel-collector-arm64:{{ .Version }}"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-arm64:latest"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-arm64:{{ .Version }}"
      # Bindplane Agent Containers
      - "observiq/bindplane-agent-arm64:latest"
      - "observiq/bindplane-agent-arm64:{{ .Version }}"
      - "ghcr.io/observiq/bindplane-agent-arm64:latest"
      - "ghcr.io/observiq/bindplane-agent-arm64:{{ .Version }}"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-arm64:latest"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-arm64:{{ .Version }}"
    dockerfile: ./docker/Dockerfile.ubuntu
    use: buildx
    build_flag_templates:
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
      - "--platform=linux/arm64"
    extra_files:
      - release_deps/VERSION.txt
      - release_deps/plugins
      - release_deps/config.yaml
      - config/logging.stdout.yaml
      - LICENSE
  - id: ubuntu-ppc64le
    goos: linux
    goarch: ppc64le
    retry:
      attempts: 10
      delay: 30s
      max_delay: 1m
    ids:
      - collector
    image_templates:
      - "observiq/observiq-otel-collector-ppc64le:latest"
      - "observiq/observiq-otel-collector-ppc64le:{{ .Version }}"
      - "ghcr.io/observiq/observiq-otel-collector-ppc64le:latest"
      - "ghcr.io/observiq/observiq-otel-collector-ppc64le:{{ .Version }}"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-ppc64le:latest"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-ppc64le:{{ .Version }}"
      # Bindplane Agent Containers
      - "observiq/bindplane-agent-ppc64le:latest"
      - "observiq/bindplane-agent-ppc64le:{{ .Version }}"
      - "ghcr.io/observiq/bindplane-agent-ppc64le:latest"
      - "ghcr.io/observiq/bindplane-agent-ppc64le:{{ .Version }}"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-ppc64le:latest"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-ppc64le:{{ .Version }}"
    dockerfile: ./docker/Dockerfile.ubuntu
    use: buildx
    build_flag_templates:
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
      - "--platform=linux/ppc64le"
    extra_files:
      - release_deps/VERSION.txt
      - release_deps/plugins
      - release_deps/config.yaml
      - config/logging.stdout.yaml
      - LICENSE

  - id: ubuntu-jmx-amd64
    goos: linux
    goarch: amd64
    retry:
      attempts: 10
      delay: 30s
      max_delay: 1m
    ids:
      - collector
    image_templates:
      - "observiq/observiq-otel-collector-amd64:{{ .Version }}-jmx"
      - "ghcr.io/observiq/observiq-otel-collector-amd64:{{ .Version }}-jmx"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-amd64:{{ .Version }}-jmx"
      # Bindplane Agent Containers
      - "observiq/bindplane-agent-amd64:{{ .Version }}-jmx"
      - "ghcr.io/observiq/bindplane-agent-amd64:{{ .Version }}-jmx"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-amd64:{{ .Version }}-jmx"
    dockerfile: ./docker/Dockerfile.jmx
    use: buildx
    build_flag_templates:
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
      - "--platform=linux/amd64"
    extra_files:
      - release_deps/VERSION.txt
      - release_deps/plugins
      - release_deps/config.yaml
      - config/logging.stdout.yaml
      - LICENSE
      - release_deps/opentelemetry-java-contrib-jmx-metrics.jar
  - id: ubuntu-jmx-arm64
    goos: linux
    goarch: arm64
    retry:
      attempts: 10
      delay: 30s
      max_delay: 1m
    ids:
      - collector
    image_templates:
      - "observiq/observiq-otel-collector-arm64:{{ .Version }}-jmx"
      - "ghcr.io/observiq/observiq-otel-collector-arm64:{{ .Version }}-jmx"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-arm64:{{ .Version }}-jmx"
      # Bindplane Agent Containers
      - "observiq/bindplane-agent-arm64:{{ .Version }}-jmx"
      - "ghcr.io/observiq/bindplane-agent-arm64:{{ .Version }}-jmx"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-arm64:{{ .Version }}-jmx"
    dockerfile: ./docker/Dockerfile.jmx
    use: buildx
    build_flag_templates:
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
      - "--platform=linux/arm64"
    extra_files:
      - release_deps/VERSION.txt
      - release_deps/plugins
      - release_deps/config.yaml
      - config/logging.stdout.yaml
      - LICENSE
      - release_deps/opentelemetry-java-contrib-jmx-metrics.jar
  - id: ubuntu-jmx-ppc64le
    goos: linux
    goarch: ppc64le
    retry:
      attempts: 10
      delay: 30s
      max_delay: 1m
    ids:
      - collector
    image_templates:
      - "observiq/observiq-otel-collector-ppc64le:{{ .Version }}-jmx"
      - "ghcr.io/observiq/observiq-otel-collector-ppc64le:{{ .Version }}-jmx"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-ppc64le:{{ .Version }}-jmx"
      # Bindplane Agent Containers
      - "observiq/bindplane-agent-ppc64le:{{ .Version }}-jmx"
      - "ghcr.io/observiq/bindplane-agent-ppc64le:{{ .Version }}-jmx"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-ppc64le:{{ .Version }}-jmx"
    dockerfile: ./docker/Dockerfile.jmx
    use: buildx
    build_flag_templates:
      - "--label=created={{.Date}}"
      - "--label=title={{.ProjectName}}"
      - "--label=revision={{.FullCommit}}"
      - "--label=version={{.Version}}"
      - "--platform=linux/ppc64le"
    extra_files:
      - release_deps/VERSION.txt
      - release_deps/plugins
      - release_deps/config.yaml
      - config/logging.stdout.yaml
      - LICENSE
      - release_deps/opentelemetry-java-contrib-jmx-metrics.jar

docker_manifests:
  - name_template: "observiq/bindplane-agent:{{ .Version }}-minimal"
    image_templates:
      - "observiq/bindplane-agent-amd64:{{ .Version }}-minimal"
      - "observiq/bindplane-agent-arm64:{{ .Version }}-minimal"
      - "observiq/bindplane-agent-ppc64le:{{ .Version }}-minimal"
    skip_push: false
  - name_template: "ghcr.io/observiq/bindplane-agent:{{ .Version }}-minimal"
    image_templates:
      - "ghcr.io/observiq/bindplane-agent-amd64:{{ .Version }}-minimal"
      - "ghcr.io/observiq/bindplane-agent-arm64:{{ .Version }}-minimal"
      - "ghcr.io/observiq/bindplane-agent-ppc64le:{{ .Version }}-minimal"
    skip_push: false
  - name_template: "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent:{{ .Version }}-minimal"
    image_templates:
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-amd64:{{ .Version }}-minimal"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-arm64:{{ .Version }}-minimal"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-ppc64le:{{ .Version }}-minimal"
    skip_push: false
  - name_template: "observiq/observiq-otel-collector:latest"
    image_templates:
      - "observiq/observiq-otel-collector-amd64:latest"
      - "observiq/observiq-otel-collector-arm64:latest"
      - "observiq/observiq-otel-collector-ppc64le:latest"
    skip_push: false
  - name_template: "observiq/observiq-otel-collector:{{ .Version }}"
    image_templates:
      - "observiq/observiq-otel-collector-amd64:{{ .Version }}"
      - "observiq/observiq-otel-collector-arm64:{{ .Version }}"
      - "observiq/observiq-otel-collector-ppc64le:{{ .Version }}"
    skip_push: false
  - name_template: "ghcr.io/observiq/observiq-otel-collector:latest"
    image_templates:
      - "ghcr.io/observiq/observiq-otel-collector-amd64:latest"
      - "ghcr.io/observiq/observiq-otel-collector-arm64:latest"
      - "ghcr.io/observiq/observiq-otel-collector-ppc64le:latest"
    skip_push: false
  - name_template: "ghcr.io/observiq/observiq-otel-collector:{{ .Version }}"
    image_templates:
      - "ghcr.io/observiq/observiq-otel-collector-amd64:{{ .Version }}"
      - "ghcr.io/observiq/observiq-otel-collector-arm64:{{ .Version }}"
      - "ghcr.io/observiq/observiq-otel-collector-ppc64le:{{ .Version }}"
    skip_push: false
  - name_template: "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector:latest"
    image_templates:
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-amd64:latest"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-arm64:latest"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-ppc64le:latest"
    skip_push: false
  - name_template: "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector:{{ .Version }}"
    image_templates:
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-amd64:{{ .Version }}"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-arm64:{{ .Version }}"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-ppc64le:{{ .Version }}"
    skip_push: false
  # Bindplane Agent Manifests
  - name_template: "observiq/bindplane-agent:latest"
    image_templates:
      - "observiq/bindplane-agent-amd64:latest"
      - "observiq/bindplane-agent-arm64:latest"
      - "observiq/bindplane-agent-ppc64le:latest"
    skip_push: false
  - name_template: "observiq/bindplane-agent:{{ .Version }}"
    image_templates:
      - "observiq/bindplane-agent-amd64:{{ .Version }}"
      - "observiq/bindplane-agent-arm64:{{ .Version }}"
      - "observiq/bindplane-agent-ppc64le:{{ .Version }}"
    skip_push: false
  - name_template: "ghcr.io/observiq/bindplane-agent:latest"
    image_templates:
      - "ghcr.io/observiq/bindplane-agent-amd64:latest"
      - "ghcr.io/observiq/bindplane-agent-arm64:latest"
      - "ghcr.io/observiq/bindplane-agent-ppc64le:latest"
    skip_push: false
  - name_template: "ghcr.io/observiq/bindplane-agent:{{ .Version }}"
    image_templates:
      - "ghcr.io/observiq/bindplane-agent-amd64:{{ .Version }}"
      - "ghcr.io/observiq/bindplane-agent-arm64:{{ .Version }}"
      - "ghcr.io/observiq/bindplane-agent-ppc64le:{{ .Version }}"
    skip_push: false
  - name_template: "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent:latest"
    image_templates:
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-amd64:latest"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-arm64:latest"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-ppc64le:latest"
    skip_push: false
  - name_template: "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent:{{ .Version }}"
    image_templates:
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-amd64:{{ .Version }}"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-arm64:{{ .Version }}"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-ppc64le:{{ .Version }}"
    skip_push: false
  # JMX Manifests
  - name_template: "observiq/observiq-otel-collector:{{ .Version }}-jmx"
    image_templates:
      - "observiq/observiq-otel-collector-amd64:{{ .Version }}-jmx"
      - "observiq/observiq-otel-collector-arm64:{{ .Version }}-jmx"
      - "observiq/observiq-otel-collector-ppc64le:{{ .Version }}-jmx"
    skip_push: false
  - name_template: "ghcr.io/observiq/observiq-otel-collector:{{ .Version }}-jmx"
    image_templates:
      - "ghcr.io/observiq/observiq-otel-collector-amd64:{{ .Version }}-jmx"
      - "ghcr.io/observiq/observiq-otel-collector-arm64:{{ .Version }}-jmx"
      - "ghcr.io/observiq/observiq-otel-collector-ppc64le:{{ .Version }}-jmx"
    skip_push: false
  - name_template: "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector:{{ .Version }}-jmx"
    image_templates:
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-amd64:{{ .Version }}-jmx"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-arm64:{{ .Version }}-jmx"
      - "us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector-ppc64le:{{ .Version }}-jmx"
    skip_push: false
  - name_template: "observiq/bindplane-agent:{{ .Version }}-jmx"
    image_templates:
      - "observiq/bindplane-agent-amd64:{{ .Version }}-jmx"
      - "observiq/bindplane-agent-arm64:{{ .Version }}-jmx"
      - "observiq/bindplane-agent-ppc64le:{{ .Version }}-jmx"
    skip_push: false
  - name_template: "ghcr.io/observiq/bindplane-agent:{{ .Version }}-jmx"
    image_templates:
      - "ghcr.io/observiq/bindplane-agent-amd64:{{ .Version }}-jmx"
      - "ghcr.io/observiq/bindplane-agent-arm64:{{ .Version }}-jmx"
      - "ghcr.io/observiq/bindplane-agent-ppc64le:{{ .Version }}-jmx"
    skip_push: false
  - name_template: "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent:{{ .Version }}-jmx"
    image_templates:
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-amd64:{{ .Version }}-jmx"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-arm64:{{ .Version }}-jmx"
      - "us-central1-docker.pkg.dev/observiq-containers/agent/bindplane-agent-ppc64le:{{ .Version }}-jmx"
    skip_push: false

# TODO(dakota): commented out because it is causing release to fail with goreleaser v2... not sure why though
# https://goreleaser.com/customization/docker_sign/
# Uses Cosign by default, signs images and manifests.
# docker_signs:
#   - artifacts: all
#     stdin: "{{ .Env.COSIGN_PWD }}"
#     args: [
#       # Default options
#       "sign",
#       "--key=cosign.key",
#       "${artifact}",
#       "--yes",
#       # Additional options
#       "--recursive"
#     ]
#     output: true
