version: 2

project_name: observiq-otel-collector

before:
  hooks:
    - make release-prep CURR_VERSION={{ .Version }}

# https://goreleaser.com/customization/build/
builds:
  - id: collector
    binary: observiq-otel-collector
    main: ./cmd/collector
    env:
      - CGO_ENABLED=1
    mod_timestamp: "{{ .CommitTimestamp }}"
    tags:
      - bindplane
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/observiq/bindplane-otel-collector/internal/version.version=v{{ .Version }}
      - -X github.com/observiq/bindplane-otel-collector/internal/version.gitHash={{ .FullCommit }}
      - -X github.com/observiq/bindplane-otel-collector/internal/version.date={{ .Date }}
    no_unique_dist_dir: false
  - id: updater
    binary: updater
    dir: ./updater/
    main: ./cmd/updater
    env:
      - CGO_ENABLED=1
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/observiq/bindplane-otel-collector/updater/internal/version.version=v{{ .Version }}
      - -X github.com/observiq/bindplane-otel-collector/updater/internal/version.gitHash={{ .FullCommit }}
      - -X github.com/observiq/bindplane-otel-collector/updater/internal/version.date={{ .Date }}
    no_unique_dist_dir: false

# https://goreleaser.com/customization/archive/
archives:
  - format: zip
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - src: release_deps/opentelemetry-java-contrib-jmx-metrics.jar
        dst: "."
        strip_parent: true
      - src: release_deps/config.yaml
        dst: "."
        strip_parent: true
      - src: release_deps/logging.yaml
        dst: "."
        strip_parent: true
      - src: release_deps/plugins/*
        dst: plugins
        strip_parent: true
      - src: release_deps/VERSION.txt
        dst: "."
        strip_parent: true
      - src: release_deps/windows_service.json
        dst: install
        strip_parent: true

# https://goreleaser.com/customization/checksum/
checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-SHA256SUMS"
  algorithm: sha256
  extra_files:
    - glob: "./observiq-otel-collector.msi"

# https://goreleaser.com/customization/sign/
signs:
  - cmd: cosign
    stdin: "{{ .Env.COSIGN_PWD }}"
    args:
      ["sign-blob", "--key=cosign.key", "--output=${signature}", "${artifact}"]
    artifacts: all

# https://goreleaser.com/customization/release/
release:
  draft: false

  # publish to a prerelease first
  prerelease: "true"
  extra_files:
    - glob: "./observiq-otel-collector*.msi"
    - glob: "./observiq-otel-collector*.msi.sig"

# https://console.cloud.google.com/storage/browser/bdot-release
blobs:
  - provider: gs
    bucket: bdot-release
    directory: "v{{ .Version }}"
    extra_files:
      - glob: "./observiq-otel-collector*.msi"
      - glob: "./observiq-otel-collector*.msi.sig"

# https://goreleaser.com/customization/changelog/
changelog:
  use: github
  sort: asc
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: "Dependencies"
      regexp: "^.*deps[(\\w)]*:+.*$"
      order: 30
    - title: Other
      order: 999
