// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/observiq/bindplane-otel-collector/extension/opampgateway")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/observiq/bindplane-otel-collector/extension/opampgateway")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                             metric.Meter
	mu                                sync.Mutex
	registrations                     []metric.Registration
	OpampgatewayDownstreamConnections metric.Int64UpDownCounter
	OpampgatewayDownstreamMessageSize metric.Int64Counter
	OpampgatewayDownstreamMessages    metric.Int64Counter
	OpampgatewayUpstreamConnections   metric.Int64UpDownCounter
	OpampgatewayUpstreamMessageSize   metric.Int64Counter
	OpampgatewayUpstreamMessages      metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.OpampgatewayDownstreamConnections, err = builder.meter.Int64UpDownCounter(
		"otelcol_opampgateway_downstream_connections",
		metric.WithDescription("The number of downstream connections."),
		metric.WithUnit("{connections}"),
	)
	errs = errors.Join(errs, err)
	builder.OpampgatewayDownstreamMessageSize, err = builder.meter.Int64Counter(
		"otelcol_opampgateway_downstream_message_size",
		metric.WithDescription("The total size of the downstream messages."),
		metric.WithUnit("B"),
	)
	errs = errors.Join(errs, err)
	builder.OpampgatewayDownstreamMessages, err = builder.meter.Int64Counter(
		"otelcol_opampgateway_downstream_messages",
		metric.WithDescription("The number of downstream messages."),
		metric.WithUnit("{messages}"),
	)
	errs = errors.Join(errs, err)
	builder.OpampgatewayUpstreamConnections, err = builder.meter.Int64UpDownCounter(
		"otelcol_opampgateway_upstream_connections",
		metric.WithDescription("The number of upstream connections."),
		metric.WithUnit("{connections}"),
	)
	errs = errors.Join(errs, err)
	builder.OpampgatewayUpstreamMessageSize, err = builder.meter.Int64Counter(
		"otelcol_opampgateway_upstream_message_size",
		metric.WithDescription("The total size of the upstream messages."),
		metric.WithUnit("B"),
	)
	errs = errors.Join(errs, err)
	builder.OpampgatewayUpstreamMessages, err = builder.meter.Int64Counter(
		"otelcol_opampgateway_upstream_messages",
		metric.WithDescription("The number of upstream messages."),
		metric.WithUnit("{messages}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
