// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("opampgateway")
	ScopeName = "github.com/observiq/bindplane-otel-collector/extension/opampgateway"
)

const (
	ExtensionStability = component.StabilityLevelAlpha
)
