// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type          = component.MustNewType("macoslogcommand")
	ScopeName     = "github.com/observiq/bindplane-otel-collector/receiver/macoslogcommandreceiver"
	LogsStability = component.StabilityLevelDevelopment
)
