// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for kandji metrics.
type MetricsConfig struct {
	KandjiAPICalls        MetricConfig `mapstructure:"kandji.api.calls"`
	KandjiAPIErrors       MetricConfig `mapstructure:"kandji.api.errors"`
	KandjiAPILatency      MetricConfig `mapstructure:"kandji.api.latency"`
	KandjiDataBytes       MetricConfig `mapstructure:"kandji.data.bytes"`
	KandjiPaginationPages MetricConfig `mapstructure:"kandji.pagination.pages"`
	KandjiRecordsReceived MetricConfig `mapstructure:"kandji.records.received"`
	KandjiScrapeDuration  MetricConfig `mapstructure:"kandji.scrape.duration"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		KandjiAPICalls: MetricConfig{
			Enabled: true,
		},
		KandjiAPIErrors: MetricConfig{
			Enabled: true,
		},
		KandjiAPILatency: MetricConfig{
			Enabled: true,
		},
		KandjiDataBytes: MetricConfig{
			Enabled: true,
		},
		KandjiPaginationPages: MetricConfig{
			Enabled: true,
		},
		KandjiRecordsReceived: MetricConfig{
			Enabled: true,
		},
		KandjiScrapeDuration: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for kandji resource attributes.
type ResourceAttributesConfig struct {
	KandjiRegion    ResourceAttributeConfig `mapstructure:"kandji.region"`
	KandjiSubdomain ResourceAttributeConfig `mapstructure:"kandji.subdomain"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		KandjiRegion: ResourceAttributeConfig{
			Enabled: true,
		},
		KandjiSubdomain: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for kandji metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
