// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("kandji")
	ScopeName = "github.com/observiq/bindplane-otel-collector/receiver/kandjireceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
