// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
		{
			name:        "filter_set_include",
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "filter_set_exclude",
			resAttrsSet: testDataSetAll,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0

			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKandjiAPICallsDataPoint(ts, 1, "endpoint-val", AttributeStatusSuccess, "http_status-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKandjiAPIErrorsDataPoint(ts, 1, "endpoint-val", AttributeReasonHTTPError)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKandjiAPILatencyDataPoint(ts, 1, "endpoint-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKandjiDataBytesDataPoint(ts, 1, "endpoint-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKandjiPaginationPagesDataPoint(ts, 1, "endpoint-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKandjiRecordsReceivedDataPoint(ts, 1, "endpoint-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordKandjiScrapeDurationDataPoint(ts, 1)

			rb := mb.NewResourceBuilder()
			rb.SetKandjiRegion("kandji.region-val")
			rb.SetKandjiSubdomain("kandji.subdomain-val")
			res := rb.Emit()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			assert.Equal(t, 1, metrics.ResourceMetrics().Len())
			rm := metrics.ResourceMetrics().At(0)
			assert.Equal(t, res, rm.Resource())
			assert.Equal(t, 1, rm.ScopeMetrics().Len())
			ms := rm.ScopeMetrics().At(0).Metrics()
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, ms.Len())
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, ms.Len())
			}
			validatedMetrics := make(map[string]bool)
			for i := 0; i < ms.Len(); i++ {
				switch ms.At(i).Name() {
				case "kandji.api.calls":
					assert.False(t, validatedMetrics["kandji.api.calls"], "Found a duplicate in the metrics slice: kandji.api.calls")
					validatedMetrics["kandji.api.calls"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Total number of Kandji API calls performed by the receiver.", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityDelta, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("endpoint")
					assert.True(t, ok)
					assert.Equal(t, "endpoint-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("status")
					assert.True(t, ok)
					assert.Equal(t, "success", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("http_status")
					assert.True(t, ok)
					assert.Equal(t, "http_status-val", attrVal.Str())
				case "kandji.api.errors":
					assert.False(t, validatedMetrics["kandji.api.errors"], "Found a duplicate in the metrics slice: kandji.api.errors")
					validatedMetrics["kandji.api.errors"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Number of Kandji API requests that failed.", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityDelta, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("endpoint")
					assert.True(t, ok)
					assert.Equal(t, "endpoint-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("reason")
					assert.True(t, ok)
					assert.Equal(t, "http_error", attrVal.Str())
				case "kandji.api.latency":
					assert.False(t, validatedMetrics["kandji.api.latency"], "Found a duplicate in the metrics slice: kandji.api.latency")
					validatedMetrics["kandji.api.latency"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Kandji API call duration per endpoint.", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("endpoint")
					assert.True(t, ok)
					assert.Equal(t, "endpoint-val", attrVal.Str())
				case "kandji.data.bytes":
					assert.False(t, validatedMetrics["kandji.data.bytes"], "Found a duplicate in the metrics slice: kandji.data.bytes")
					validatedMetrics["kandji.data.bytes"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Total number of bytes returned in Kandji API responses.", ms.At(i).Description())
					assert.Equal(t, "By", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityDelta, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("endpoint")
					assert.True(t, ok)
					assert.Equal(t, "endpoint-val", attrVal.Str())
				case "kandji.pagination.pages":
					assert.False(t, validatedMetrics["kandji.pagination.pages"], "Found a duplicate in the metrics slice: kandji.pagination.pages")
					validatedMetrics["kandji.pagination.pages"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Number of pagination pages processed for Kandji API calls.", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityDelta, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("endpoint")
					assert.True(t, ok)
					assert.Equal(t, "endpoint-val", attrVal.Str())
				case "kandji.records.received":
					assert.False(t, validatedMetrics["kandji.records.received"], "Found a duplicate in the metrics slice: kandji.records.received")
					validatedMetrics["kandji.records.received"] = true
					assert.Equal(t, pmetric.MetricTypeSum, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Sum().DataPoints().Len())
					assert.Equal(t, "Number of records returned from Kandji API responses.", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					assert.True(t, ms.At(i).Sum().IsMonotonic())
					assert.Equal(t, pmetric.AggregationTemporalityDelta, ms.At(i).Sum().AggregationTemporality())
					dp := ms.At(i).Sum().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("endpoint")
					assert.True(t, ok)
					assert.Equal(t, "endpoint-val", attrVal.Str())
				case "kandji.scrape.duration":
					assert.False(t, validatedMetrics["kandji.scrape.duration"], "Found a duplicate in the metrics slice: kandji.scrape.duration")
					validatedMetrics["kandji.scrape.duration"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Duration of the entire Kandji scrape cycle.", ms.At(i).Description())
					assert.Equal(t, "ms", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
				}
			}
		})
	}
}
