// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for s3event resource attributes.
type ResourceAttributesConfig struct {
	AwsS3Bucket ResourceAttributeConfig `mapstructure:"aws.s3.bucket"`
	AwsS3Key    ResourceAttributeConfig `mapstructure:"aws.s3.key"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		AwsS3Bucket: ResourceAttributeConfig{
			Enabled: true,
		},
		AwsS3Key: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}
