// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetGcsBucket sets provided value as "gcs.bucket" attribute.
func (rb *ResourceBuilder) SetGcsBucket(val string) {
	if rb.config.GcsBucket.Enabled {
		rb.res.Attributes().PutStr("gcs.bucket", val)
	}
}

// SetGcsObject sets provided value as "gcs.object" attribute.
func (rb *ResourceBuilder) SetGcsObject(val string) {
	if rb.config.GcsObject.Enabled {
		rb.res.Attributes().PutStr("gcs.object", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
