// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetAwsS3Bucket sets provided value as "aws.s3.bucket" attribute.
func (rb *ResourceBuilder) SetAwsS3Bucket(val string) {
	if rb.config.AwsS3Bucket.Enabled {
		rb.res.Attributes().PutStr("aws.s3.bucket", val)
	}
}

// SetAwsS3Key sets provided value as "aws.s3.key" attribute.
func (rb *ResourceBuilder) SetAwsS3Key(val string) {
	if rb.config.AwsS3Key.Enabled {
		rb.res.Attributes().PutStr("aws.s3.key", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
