name: manual_msi_build
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Collector Version"
        required: true
        default: "v0.0.1"
      build_amd64:
        description: "Build amd64 MSI"
        type: boolean
        default: true
      build_arm64:
        description: "Build arm64 MSI"
        type: boolean
        default: true

jobs:
  build-msi:
    uses: ./.github/workflows/build-signed-windows.yml
    with:
      version: ${{ inputs.version }}
      build_amd64: ${{ inputs.build_amd64 }}
      build_arm64: ${{ inputs.build_arm64 }}
    secrets: inherit
