name: Test GCS Release Bucket
on:
  workflow_dispatch:

jobs:
  test_gcs_release_bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Install Gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.BDOT_GCS_RELEASE_BUCKET_PROJECT_ID }}
          credentials_json: ${{ secrets.BDOT_GCS_RELEASE_BUCKET_CREDENTIALS }}
      - name: Test Gsutil
        run: gsutil ls gs://bdot-release
