name: Release Test (GPG)
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Collector Version"
        required: true
        default: "v0.0.1"

jobs:
  release-test:
    runs-on: namespace-profile-bindplane-default-ubuntu-24-04-32x128
    steps:
      - name: Checkout Repo
        uses: namespacelabs/nscloud-checkout-action@v7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false # Use Namespace caching instead
      - name: Set up Go cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: go
        
      - name: Fake Windows MSI
        run: touch ./observiq-otel-collector.msi

      - name: Set VERSION
        run: echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Write signing key for nFPM
        shell: bash
        run: |
          cat > ci-signing-key.asc <<'EOF'
          ${{ secrets.TEMP_2025_GPG_PRIVATE_KEY }}
          EOF

      - name: Cache Goreleaser Build
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: ~/.cache/goreleaser

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: "v2.12.5"
          args: release --skip=publish --clean
        env:
          GORELEASER_CURRENT_TAG: ${{ env.VERSION }}
          GITHUB_TOKEN: ${{ secrets.ORG_GORELEASER_GITHUB_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          SIGNING_KEY_FILE: ci-signing-key.asc

      - name: Upload build artifacts
        uses: namespace-actions/upload-artifact@v1
        with:
          name: dist-artifacts
          path: dist/
          retention-days: 1