name: 'Close stale PRs'
on:
  schedule:
    # Runs at 1:30 AM UTC every day
    - cron: '30 1 * * *'
  workflow_dispatch: # For manual testing

permissions:
  actions: write
  contents: read # Don't need write unless we want to delete the branch
  issues: write
  pull-requests: write

jobs:
  stale:
    uses: observIQ/gha-workflows/.github/workflows/stale.yaml@main
